import Link from "next/link";
import { ArrowRight, BrainCircuit, CheckCircle2, GraduationCap, ShieldCheck, Sparkles } from "lucide-react";

import { BrandMark } from "@/components/shared/brand-mark";
import { Button } from "@/components/ui/button";
import { t } from "@/i18n";

export default function Home() {
  return (
    <main className="min-h-screen bg-[radial-gradient(circle_at_15%_10%,rgba(21,101,192,0.14),transparent_30%),radial-gradient(circle_at_85%_5%,rgba(46,125,50,0.12),transparent_25%),#f8fbff] text-[color:var(--navy)]">
      <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-6 sm:px-8"><BrandMark /><nav className="flex items-center gap-3"><Link href="/login" className="hidden text-sm font-medium text-muted-foreground hover:text-foreground sm:inline">Kirish</Link><Button asChild><Link href="/register">Bepul boshlash<ArrowRight data-icon="inline-end" /></Link></Button></nav></header>
      <section className="mx-auto grid max-w-7xl gap-12 px-5 pb-20 pt-12 sm:px-8 lg:grid-cols-[1.05fr_0.95fr] lg:items-center lg:pt-20"><div><p className="mb-5 text-sm font-semibold tracking-[0.18em] text-primary uppercase">{t("homeEyebrow")}</p><h1 className="max-w-3xl font-heading text-4xl font-semibold tracking-tight sm:text-6xl">{t("homeTitle")}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">{t("homeDescription")}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild className="h-11"><Link href="/register">Bepul boshlash<ArrowRight data-icon="inline-end" /></Link></Button><Button asChild className="h-11" variant="outline"><Link href="/login">Platformani ko‘rish</Link></Button></div><p className="mt-5 text-sm text-muted-foreground">{t("homeAccessNote")}</p></div><div className="relative rounded-3xl border border-white/80 bg-white/80 p-5 shadow-[0_30px_80px_-42px_rgba(15,42,74,0.65)] backdrop-blur"><div className="rounded-2xl bg-[color:var(--navy)] p-6 text-white"><div className="flex items-center justify-between"><span className="text-sm text-white/70">UniLoop evidence loop</span><Sparkles className="size-5 text-emerald-300" /></div><p className="mt-8 text-3xl font-semibold">60% → 90%</p><p className="mt-2 text-sm text-white/70">Dalil asosida keyingi qadam</p><div className="mt-8 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-white/10 p-4"><BrainCircuit className="size-5 text-sky-300" /><p className="mt-3 text-sm font-medium">O‘zlashtirish</p><p className="mt-1 text-xs text-white/60">Natijadan amaliy reja</p></div><div className="rounded-xl bg-white/10 p-4"><ShieldCheck className="size-5 text-emerald-300" /><p className="mt-3 text-sm font-medium">Ishonchli dalil</p><p className="mt-1 text-xs text-white/60">Rozilik va nazorat bilan</p></div></div></div></div></section>
      <section className="border-y border-border/70 bg-white/70"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-16 sm:px-8 md:grid-cols-3"><div><GraduationCap className="size-7 text-primary" /><h2 className="mt-4 font-heading text-xl font-semibold">Talaba uchun</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Baholashdagi bo‘shliqlarni ko‘ring, aniq o‘quv vazifalarini bajaring va qobiliyatingizni dalil bilan ko‘rsating.</p></div><div><BrainCircuit className="size-7 text-primary" /><h2 className="mt-4 font-heading text-xl font-semibold">Professor uchun</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Guruh naqshlarini tushuning, kerakli aralashuvni tanlang va talabaning o‘sishini qo‘llab-quvvatlang.</p></div><div><CheckCircle2 className="size-7 text-primary" /><h2 className="mt-4 font-heading text-xl font-semibold">Ishonchli AI</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">AI tushuntiradi va tavsiya qiladi; baho, o‘zlashtirish va ruxsat qarorlarini insonlar hamda deterministik xizmatlar boshqaradi.</p></div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-16 text-center sm:px-8"><h2 className="font-heading text-3xl font-semibold">Keyingi o‘quv qadamni bugun boshlang.</h2><p className="mx-auto mt-3 max-w-xl text-muted-foreground">Talaba yoki professor sifatida bepul hisob yarating.</p><div className="mt-7 flex justify-center"><Button asChild className="h-11"><Link href="/register">Hisob yaratish<ArrowRight data-icon="inline-end" /></Link></Button></div></section>
    </main>
  );
}
